name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Usa Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'  

      - name: Installa dipendenze
        run: npm ci

      - name: Run tests con coverage
        run: npm test -- --coverage

      - name: Upload report coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage  
